/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2016-12-10 18:10:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.homepage.guestbook;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import guestbook.*;

public final class guestbook_005fcontrol_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- 게시의 등록, 수정을 위해  자바빈즈 이용 선언-->\n");
      out.write("\t");
      guestbook.GuestBean brd = null;
      brd = (guestbook.GuestBean) _jspx_page_context.getAttribute("brd", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (brd == null){
        brd = new guestbook.GuestBean();
        _jspx_page_context.setAttribute("brd", brd, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write(" \n");
      out.write("\t    \n");
      out.write("\t");
 
		GuestMgr brddb = new GuestMgr();
		request.setCharacterEncoding("euc-kr");
	 	String menu = request.getParameter("menu"); 
		
	 	if (menu.equals("update") ) { 
			String gb_num = request.getParameter("gb_num");
			String gb_passwd = request.getParameter("gb_passwd");
			int inum = Integer.parseInt(gb_num);	
			    
			if ( !brddb.isPasswd(inum, gb_passwd) ) {
	
      out.write("\n");
      out.write("\t\t\t\t<!-- 암호가 틀리면 이전 화면으로 이동 -->\n");
      out.write("\t\t\t\t<script>alert(\"비밀번호가 다릅니다.\"); history.go(-1);</script>\n");
      out.write("\t");

			} else {
	
      out.write("\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("brd"), "gb_num", request.getParameter("gb_num"), request, "gb_num", false);
      out.write("\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("brd"), "gb_name", request.getParameter("gb_name"), request, "gb_name", false);
      out.write("\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("brd"), "gb_content", request.getParameter("gb_content"), request, "gb_content", false);
      out.write('\n');
      out.write('\n');
      out.write('	');
					
					brddb.updateBoard(brd);				
					response.sendRedirect("guestbook_list.jsp");					 		
			}
	 	} else if ( menu.equals("insert") ) {  
	
      out.write("\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("brd"), "gb_name", request.getParameter("gb_name"), request, "gb_name", false);
      out.write("\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("brd"), "gb_content", request.getParameter("gb_content"), request, "gb_content", false);
      out.write("\n");
      out.write("\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.introspecthelper(_jspx_page_context.findAttribute("brd"), "gb_passwd", request.getParameter("gb_passwd"), request, "gb_passwd", false);
      out.write('\n');
      out.write('\n');
      out.write('	');
				
			brddb.insertBoard(brd);
			response.sendRedirect("guestbook_list.jsp");					 		
	 	}
	
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
