/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2016-12-10 19:14:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.homepage.guestbook;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Vector;
import guestbook.*;
import java.text.SimpleDateFormat;

public final class guestbook_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/homepage/common.jsp", out, false);
      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"EUC-KR\"/>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" \n");
      out.write("integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\n");
      out.write("<script\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.1.1.min.js\"\n");
      out.write("  integrity=\"sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=\"\n");
      out.write("  crossorigin=\"anonymous\"></script>\n");
      out.write("<!-- Optional theme -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" integrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\" integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\" crossorigin=\"anonymous\"></script>\n");
      out.write("<!-- 파일 boardForm.js : 폼의 각 입력 값이 있는지를 검토하는 함수 구현 -->\n");
      out.write("<script language=JavaScript src=\"boardForm.js\"></script>\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<center>\n");
      out.write("\t<div class=\"wrapper\">\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/homepage/head.jsp", out, false);
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"content\">\n");
      out.write("\t\t<h2>한줄 방명록 </h2>\n");
      out.write("\t\t<hr>  \n");
      out.write("\t\t<center>\n");
      out.write("\t\t\t");
 
				
				String num = request.getParameter("gb_num");
				
				GuestMgr brddb = new GuestMgr();	 	
				Vector<GuestBean> list = brddb.getBoardList(); 
			   	int counter = list.size();
			   	int row = 0;
			   	
			   	if (counter > 0) {
			
      out.write("\n");
      out.write("\t\t    <table width=800  cellpadding=3 cellspacing=3 >\n");
      out.write("\t\t    \n");
      out.write("\t\t    <tr>\n");
      out.write("\t\t       <td align=center width=60 bgcolor=lightgray><font color=blue><b>번호</b></font></td>\n");
      out.write("\t\t       <td align=center width=80 bgcolor=lightgray><font color=blue><b>작성자</b></font></td>\n");
      out.write("\t\t       <td align=center width=170 bgcolor=lightgray><font color=blue><b>작성일</b></font></td>\n");
      out.write("\t\t       <td align=center width=170 bgcolor=lightgray><font color=blue><b>내용</b></font></td>\n");
      out.write("\t\t    </tr>\n");
      out.write("\t\t\t");

				//게시 등록일을 2010-3-15 10:33:21 형태로 출력하기 위한 클래스 
				SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
				for( GuestBean brd : list ) {

			
      out.write("\n");
      out.write("\t\t    <tr> \n");
      out.write("\t\t\t\t<!-- 수정과 삭제를 위한 링크로 id를 전송 -->\n");
      out.write("\t\t       <td align=center>");
      out.print( brd.getGb_num());
      out.write("</td>\n");
      out.write("\t\t       <td align=center>");
      out.print( brd.getGb_name() );
      out.write("</td>\n");
      out.write("\t\t\t\t<!-- 게시 작성일을 2010-3-15 10:33:21 형태로 출력 -->\n");
      out.write("\t\t       <td align=center>");
      out.print( df.format(brd.getGb_date()) );
      out.write("</td>\n");
      out.write("\t\t       <td align=center>");
      out.print( brd.getGb_content() );
      out.write("</td>\n");
      out.write("\t\t\t     <td>\n");
      out.write("\t\t\t  \t\t<input class=\"btn btn-primary\" type=button value=\"수정\" onClick=\"location.href='guest_edit_form.jsp?num=");
      out.print(num);
      out.write("'\">\n");
      out.write("\t\t\t  \t</td>\n");
      out.write("\t\t\t  \t<td>\n");
      out.write("\t\t\t    \t<input class=\"btn btn-danger\" type=button value=\"삭제\" onClick=\"deleteConfirm(");
      out.print(num);
      out.write(")\"> \n");
      out.write("\t\t\t\t </td>\n");
      out.write("\t\t\t    </tr> \n");
      out.write("\t\t\t");

			    }  
			
      out.write("\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t");
 	}
		
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t<hr width=80%>\n");
      out.write("\t\t<p>조회된 게시판 목록 수가 ");
      out.print(counter);
      out.write("개 입니다.\n");
      out.write("\t\t<br><br>\n");
      out.write("\t\t<form name=form method=post action=\"guestbook_form.jsp\">\n");
      out.write("\t\t      <input class=\"btn btn-success\" type=submit value=\"글쓰기\"> \n");
      out.write("\t\t</form>\n");
      out.write("\t\t</center>\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"foot\">\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/homepage/foot.jsp", out, false);
      out.write("\n");
      out.write("\t</div>\n");
      out.write("</center>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
