/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2016-12-10 06:31:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.homepage.noticeboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import noticeboard.*;

public final class noticeeditBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" \r\n");
      out.write("integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.1.1.min.js\"\r\n");
      out.write("  integrity=\"sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- Optional theme -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" integrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\" integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- 파일 boardForm.js : 폼의 각 입력 값이 있는지를 검토하는 함수 구현 -->\r\n");
      out.write("<script language=JavaScript src=\"noticeboardForm.js\"></script>\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/homepage/head.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div id=\"content\">\r\n");
      out.write("\t\t\t");

		String name = ""; 
		String email = ""; 
		String title = ""; 
		String content = "";
		String headline = "insert";
		
		String num = request.getParameter("num");
		if (num != null) { 
			int idnum = Integer.parseInt(num);
			
			NoticeMgr beandb = new NoticeMgr(); 
			NoticeBean bean = beandb.getBoard(idnum);  
			name = bean.getName();
			email = bean.getEmail();
			title = bean.getTitle();
			content = bean.getContent();
			headline = "update";
		};
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<h2>게시판 ");
      out.print(headline );
      out.write("  </h2> <hr>\r\n");
      out.write("\t\r\n");
      out.write("\t<center>\r\n");
      out.write("\t<form name=boardForm method=post action=\"noticeprocessBoard.jsp\" >\r\n");
      out.write("\t<!-- 수정:  게시 id를 hidden으로 전송 -->\r\n");
      out.write("\t<input type=hidden name=\"num\" value=");
      out.print(num );
      out.write(">\r\n");
      out.write("\t<input type=hidden name=\"menu\" value=\"insert\">\r\n");
      out.write("\t<table width=700 border=0 cellspacing=0 cellpadding=7>\r\n");
      out.write("\t <tr>\r\n");
      out.write("\t  <td align=center>\r\n");
      out.write("\t\t<table >\r\n");
      out.write("\t\t\t<tr> \r\n");
      out.write("\t\t\t\t<td colspan=2>\r\n");
      out.write("\t\t\t\t\t<table  width=650>\r\n");
      out.write("\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t\t     <td  align=left>이 름: </td>\r\n");
      out.write("\t\t\t\t\t\t     <td align=left>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=text name=name value=\"");
      out.print(name);
      out.write("\" size=30 maxlength=20></td>\r\n");
      out.write("\t\t\t\t\t\t     <td  align=left>전자메일:</td>\r\n");
      out.write("\t\t\t\t\t\t     <td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=text name=email size=30 value=\"");
      out.print(email);
      out.write("\" maxlength=30 ></td>\r\n");
      out.write("\t\t\t\t\t    </tr>\t\r\n");
      out.write("\t\t\t\t\t\t<tr >\r\n");
      out.write("\t\t\t\t\t     <td align=left>제 목: </td>\r\n");
      out.write("\t\t\t\t\t     <td colspan=3 align=left>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=text name=title size=80 value=\"");
      out.print(title);
      out.write("\" maxlength=100></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td> \r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t\t    <td colspan=2 align=left>\r\n");
      out.write("\t\t\t\t\t\t<textarea name=content rows=10 cols=90>");
      out.print(content);
      out.write("</textarea></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t    <td colspan=2 align=left>비밀번호 :\r\n");
      out.write("\t\t\t\t     <input type=password name=passwd size=20 maxlength=20><font color=red>  \r\n");
      out.write("\t\t\t         \t게시 내용을 수정 또는 삭제하려면 비밀번호가 필요합니다.</font></td>\r\n");
      out.write("\t\t    </tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t     \t<td colspan=2 height=5><hr size=2></td>\r\n");
      out.write("\t\t    </tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t     <td colspan=2>\r\n");
      out.write("\t\t\t\t\t");
 if (num == null) { 
      out.write("\t\r\n");
      out.write("\t\t\t\t\t \t\t<input type=button value=\"등록\" onClick=\"insertCheck()\">\r\n");
      out.write("\t\t\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t  \t\t\t\t<input type=button value=\"수정완료\" onClick=\"updateCheck()\">\t\t\t    \t\r\n");
      out.write("\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=button value=\"목록보기\" onClick=\"location.href='noticelistBoard.jsp'\"> \t\t\t\t\r\n");
      out.write("\t\t\t\t </td>\r\n");
      out.write("\t\t    </tr> \r\n");
      out.write("\t   \t</table> \r\n");
      out.write("\t   </td>\r\n");
      out.write("\t </tr> \t \t\r\n");
      out.write("\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</center>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"foot\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/homepage/foot.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
