/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2016-12-10 07:20:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.homepage.noticeboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import noticeboard.*;
import java.text.SimpleDateFormat;

public final class noticereadBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" \r\n");
      out.write("integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.1.1.min.js\"\r\n");
      out.write("  integrity=\"sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- Optional theme -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" integrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\" integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script >\r\n");
      out.write("\r\n");
      out.write("function deleteConfirm(num) {\r\n");
      out.write("\tok = confirm(\"삭제하시겠습니까?\");\r\n");
      out.write("\tif (ok) {\r\n");
      out.write("\t\tlocation.href = \"noticepasswordBoard.jsp?num=\" + num ;\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\t\t\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/homepage/head.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div id=\"content\">\r\n");
      out.write("\t\t");

		String name = ""; 
		String email = "";
		String regdate = "";
		String hit = "";
		String title = ""; 
		String content = "";
		
		
		String num = request.getParameter("num");
		
		if (num != null) {	
			int inum = Integer.parseInt(num);
			NoticeMgr brddb = new NoticeMgr(); 
			brddb.updateHit(inum);
			NoticeBean brd = brddb.getBoard(inum); 
			
			name = brd.getName();
			email = brd.getEmail();
			SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
			regdate = df.format( brd.getRegdate());
			hit = Integer.toString( brd.getHit());
			title = brd.getTitle();
			content = brd.getContent();
		};
	
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t<h2>게시판 보기 프로그램 </h2> <hr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div align=center>\r\n");
      out.write("\t\t<table width=700 border=0 cellspacing=0 cellpadding=7>\r\n");
      out.write("\t\t <tr><td align=center>\r\n");
      out.write("\t\t \t <table border=0>\r\n");
      out.write("\t\t \t   <tr>\r\n");
      out.write("\t\t \t    <td>\r\n");
      out.write("\t\t\t\t\t<table width=650 border=1 cellspacing=0 cellpadding=5 >\r\n");
      out.write("\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t     <td width=100 bgcolor=papayawhip align=left>이 름  </td>\r\n");
      out.write("\t\t\t\t\t     <td width=180 align=left>");
      out.print(name );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t\t     <td width=100 bgcolor=papayawhip align=left>전자메일 </td>\r\n");
      out.write("\t\t\t\t\t     <td align=left >");
      out.print(email );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t    </tr>\t\r\n");
      out.write("\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t     <td width=100 bgcolor=papayawhip align=left>작성일 </td>\r\n");
      out.write("\t\t\t\t\t     <td width=180 align=left>");
      out.print(regdate );
      out.write(" </td>\r\n");
      out.write("\t\t\t\t\t     <td width=100 bgcolor=papayawhip align=left>조회수</td>\r\n");
      out.write("\t\t\t\t\t     <td align=left>");
      out.print(hit );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t    </tr>\t\r\n");
      out.write("\t\t\t\t\t\t<tr >\r\n");
      out.write("\t\t\t\t\t     <td width=100  bgcolor=papayawhip align=left>제 목 </td>\r\n");
      out.write("\t\t\t\t\t     <td colspan=3 align=left>");
      out.print(title );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t    <tr height=300><td colspan=4 align=left valign=top>");
      out.print(content);
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t <td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t     <td height=20 colspan=4></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t     <td colspan=4>\r\n");
      out.write("\t\t\t  \t\t<input type=button value=\"수정\" onClick=\"location.href='noticeeditBoard.jsp?num=");
      out.print(num);
      out.write("'\">\r\n");
      out.write("\t\t\t    \t\t<input type=button value=\"삭제\" onClick=\"deleteConfirm(");
      out.print(num);
      out.write(")\"/>\r\n");
      out.write("\t\t\t\t\t<!-- 목록보기 버튼은 listboard.jsp로 이동 -->\r\n");
      out.write("\t\t\t\t\t<input type=button value=\"목록보기\" onClick=\"location.href='noticelistBoard.jsp'\">\r\n");
      out.write("\t\t\t\t </td>\r\n");
      out.write("\t\t\t    </tr> \r\n");
      out.write("\t\t   \t</table>\r\n");
      out.write("\t\t  </td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"foot\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/homepage/foot.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
