/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2016-12-09 21:27:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.homepage.guestboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class guest_005fedit_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"guestbook_error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
 response.setCharacterEncoding("utf-8"); 
      out.write('\n');
      guestboard.GuestBean gb = null;
      gb = (guestboard.GuestBean) _jspx_page_context.getAttribute("gb", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (gb == null){
        gb = new guestboard.GuestBean();
        _jspx_page_context.setAttribute("gb", gb, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.introspect(_jspx_page_context.findAttribute("gb"), request);
      out.write('\n');
      out.write('\n');

 gb.selectDB();
 if(!gb.checkPasswd(request.getParameter("gb_passwd"))){
     out.println("<script> alert('Incorrect Password'); history.go(-1); </script>");
 }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>방명록</title>\n");
      out.write("        <script language=\"javascript\">\n");
      out.write("            function del_confirm(){\n");
      out.write("                yn = confirm(\"Delete Sure?\");\n");
      out.write("                if(yn){\n");
      out.write("                    form1.action.value=\"delete\";\n");
      out.write("                    form1.submit();\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            </script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("    <center>\n");
      out.write("        <h1>방명록 : 수정하기</h1>\n");
      out.write("        <form name=\"form1\" method=\"post\" action=\"guestbook_control.jsp\">\n");
      out.write("            <input type=\"hidden\" name=\"action\" value=\"update\">\n");
      out.write("            <input type=\"hidden\" name=\"gb_id\" value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((guestboard.GuestBean)_jspx_page_context.findAttribute("gb")).getGb_id())));
      out.write("\">\n");
      out.write("            \n");
      out.write("            <table cellpadding=\"5\" cellspacing=\"0\" border=\"1\">\n");
      out.write("                <tr>\n");
      out.write("                    <td bgcolor=\"#99CCFF\">작 성 자</td>\n");
      out.write("                    <td><input type=\"text\" name=\"gb_name\" size=\"20\" value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((guestboard.GuestBean)_jspx_page_context.findAttribute("gb")).getGb_name())));
      out.write("\"></td>\n");
      out.write("                </tr>\n");
      out.write("                \n");
      out.write("                <tr>\n");
      out.write("                    <td bgcolor=\"#99CCFF\">email</td>\n");
      out.write("                    <td><input type=\"text\" name=\"gb_email\" size=\"20\" value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((guestboard.GuestBean)_jspx_page_context.findAttribute("gb")).getGb_email())));
      out.write("\"></td>\n");
      out.write("                </tr>\n");
      out.write("                \n");
      out.write("                <tr>\n");
      out.write("                    <td bgcolor=\"#99CCFF\">비밀번호</td>\n");
      out.write("                    <td><input type=\"password\" name=\"gb_passwd\" size=\"20\" value=\"");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((guestboard.GuestBean)_jspx_page_context.findAttribute("gb")).getGb_passwd())));
      out.write("\"></td>\n");
      out.write("                </tr>\n");
      out.write("                \n");
      out.write("                <tr>\n");
      out.write("                    <td colspan=\"2\"><textarea rows=\"5\" name=\"gb_contents\" cols=\"40\">");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((guestboard.GuestBean)_jspx_page_context.findAttribute("gb")).getGb_contents())));
      out.write("</textarea></td>\n");
      out.write("                </tr>\n");
      out.write("                \n");
      out.write("                <tr>\n");
      out.write("                    <td colspan=\"2\" align=\"center\">\n");
      out.write("                        <input type=\"submit\" value=\"저장\">\n");
      out.write("                        <input type=\"reset\" value=\"취소\">\n");
      out.write("                        <input type=\"button\" value=\"삭제\" onClick=\"del_confirm()\">                        \n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("        </form>\n");
      out.write("                <a href =\"guestbook_list.jsp\">목록으로</a>\n");
      out.write("    </center>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
