/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2016-12-09 21:23:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.homepage.guestboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class guestbook_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"guestbook_error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
 response.setCharacterEncoding("utf-8"); 
      out.write('\n');
      out.write('\n');
      guestboard.GuestBean gb = null;
      gb = (guestboard.GuestBean) _jspx_page_context.getAttribute("gb", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (gb == null){
        gb = new guestboard.GuestBean();
        _jspx_page_context.setAttribute("gb", gb, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\n');
      out.write('\n');

 ArrayList datas = gb.selectDBList();
 Iterator iter = datas.iterator();

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>방명록</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("    <center>\n");
      out.write("        <h1> 방명록 </h1>\n");
      out.write("        <hr>\n");
      out.write("        <a href=\"guestbook_form.jsp\">방명록 쓰기</a><p>\n");
      out.write("                ");

                 while(iter.hasNext()){
                     HashMap data = (HashMap)iter.next();
                 
                
      out.write("\n");
      out.write("        <form name=\"");
      out.print( data.get("gb_id"));
      out.write("\" action=\"guest_edit_form.jsp\" method=\"post\">\n");
      out.write("            <input type=\"hidden\" name=\"gb_id\" value=\"");
      out.print( data.get("gb_id") );
      out.write("\" >\n");
      out.write("            \n");
      out.write("            <table cellpadding=\"5\" cellspacing=\"0\" border=\"1\" width=\"400\">\n");
      out.write("                <tr>\n");
      out.write("                    <td bgcolor=\"#99CCFF\" height=\"23\">작 성 자</td>\n");
      out.write("                    <td>");
      out.print( data.get("gb_name") );
      out.write("</td>\n");
      out.write("                    <td bgcolor=\"#99CCFF\" height=\"23\">작 성 일</td>\n");
      out.write("                    <td>");
      out.print( data.get("gb_date") );
      out.write("</td>\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                \n");
      out.write("                <tr>\n");
      out.write("                    <td bgcolor=\"#99CCFF\" height=\"23\">email</td>\n");
      out.write("                    <td colspan=\"3\">");
      out.print( data.get("gb_email") );
      out.write("</td>\n");
      out.write("                </tr>\n");
      out.write("                \n");
      out.write("                <tr>\n");
      out.write("                    <td colspan=\"4\">");
      out.print( data.get("gb_contents") );
      out.write("</td>\n");
      out.write("                </tr>\n");
      out.write("                \n");
      out.write("                <tr>\n");
      out.write("                    <td colspan=\"4\">비밀번호 <input type=\"password\" name=\"gb_passwd\" size=\"6\">\n");
      out.write("                        <input type=\"submit\" value=\"수정/삭제\"></td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("            </p>\n");
      out.write("        </form>\n");
      out.write("                <p>\n");
      out.write("                    ");

                      }
                    
      out.write("\n");
      out.write("    </center>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
