/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2016-12-09 18:53:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.homepage.guestboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import javax.naming.*;
import java.text.SimpleDateFormat;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>방명록</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=euc-kr\">\r\n");
      out.write("<link href=\"../css/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
 
request.setCharacterEncoding("euc-kr");	
	response.setCharacterEncoding("euc-kr");
	
	String query_count="select count(*) from guestbook";
	String query_list="select *from (select rownum rseq,seq,name,email,homepage,subject,content,logtime from guestbook where rownum<=?) A where A.rseq > ? order by logtime desc";

	int pageSize = 5;
	int cpage=1;
	int total=0;
	
	SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
	
	try{
		cpage= Integer.parseInt(request.getParameter("pg"));
		
	}catch(Exception e){
		cpage=1;
	}
	Context initCtx=new InitialContext();
	Context envCtx=(Context)initCtx.lookup("java:comp/env");
	DataSource ds=(DataSource)envCtx.lookup("jdbc/oraclePool");
	Connection conn=null;
	PreparedStatement pstmt= null;
	ResultSet rs=null;
	
	try{
		conn=ds.getConnection();
		pstmt=conn.prepareStatement(query_count);
		rs=pstmt.executeQuery();
		if(rs.next()){
			
			total=rs.getInt(1);
		}
		rs.close();
		pstmt.close();
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("  <!-- 방명록 헤더 -->\r\n");
      out.write("  <table width=\"85%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td class=\"header\">방명록</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("  \r\n");
      out.write("  <br>\r\n");
      out.write("  <table width=\"85%\">\r\n");
      out.write("  \t<tr>\r\n");
      out.write("  \t\t<td>&nbsp;</td>\r\n");
      out.write("  \t\t<td align=\"right\">\r\n");
      out.write("  \t\t\t<a href=\"write.jsp\">글쓰기</a>\r\n");
      out.write("  \t\t</td>\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t</tr>\r\n");
      out.write("  \r\n");
      out.write("  </table>\r\n");
      out.write("  <!--  방명록 표시 -->\r\n");
      out.write("  <table width=\"85%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("  ");

  	int endNo=pageSize * cpage;
    pstmt=conn.prepareStatement(query_list);
    pstmt.setInt(1, endNo);
    pstmt.setInt(2, endNo-pageSize);
    rs=pstmt.executeQuery();
    
    while(rs.next()){

  
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    <tr>\r\n");
      out.write("      <td height=\"20\" class=\"title\">작성자: ");
      out.print(rs.getString("name") );
      out.write(" \r\n");
      out.write("      ");
if(rs.getString("email")!=null) {
      out.write("\r\n");
      out.write("        <a href=\"mailto:");
      out.print(rs.getString("email"));
      out.write("\">\r\n");
      out.write("        <img src=\"/../img/email.gif\" alt=\"이메일\" width=\"24\" height=\"24\" border=\"0\" align=\"absbottom\"></a>");
} 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
if(rs.getString("homepage")!=null) { 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        <a href=\"");
      out.print(rs.getString("homepage"));
      out.write("\"><img src=\"../../images/homepage.gif\" alt=\"홈페이지\" width=\"14\" height=\"14\" border=\"0\" align=\"absbottom\"></a></td>\r\n");
      out.write("    \t");
} 
      out.write("\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("    \t\r\n");
      out.write("      <td class=\"content\">\r\n");
      out.write("      <b>");
      out.print(rs.getString("subject") );
      out.write("</b><br>\r\n");
      out.write("      ");
      out.print(rs.getString("content") );
      out.write("<br>\r\n");
      out.write("      <p class=\"content\" align=\"right\">");
      out.print(sdf.format(rs.getTimestamp("logtime")) );
      out.write("</p>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td align=\"right\">\r\n");
      out.write("      <a href=\"password.jsp?seq=");
      out.print(rs.getInt("seq"));
      out.write("\">삭제\r\n");
      out.write("      </a></td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    ");

    
    }//end of while
    
    
      out.write("\r\n");
      out.write("   \r\n");
      out.write("  </table>\r\n");
      out.write("  \r\n");
      out.write("  ");

	}catch(Exception e){
		e.printStackTrace();
	}finally{
		if(conn!=null)conn.close();
	}
	
	
	
      out.write("\r\n");
      out.write("  <!--  page 표시 -->\r\n");
      out.write("  <table width=\"85%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td align=\"center\" class=\"page\">");

    int totalPage = (total-1)/pageSize + 1;
    int prev10 = (int)Math.floor((cpage-1) / 10.0) * 10;
    int next10 = prev10 + 11;

      out.write("\r\n");
      out.write("  <table width=\"85%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td align=\"center\" class=\"page\">\r\n");
      out.write("<a href=\"list.jsp?pg=1\">top</a>\r\n");

    if (prev10 > 0) {

      out.write("\r\n");
      out.write("\t<a href=\"list.jsp?pg=");
      out.print( prev10 );
      out.write("\">이전</a>");

    }

    for (int i=1+prev10; i< next10 && i<=totalPage; i++ ) {
    	if (i==cpage) {

      out.write(" \r\n");
      out.write("\t[<b>");
      out.print( i );
      out.write("</b>]\r\n");
      out.write("\r\n");

    	} else {

      out.write(" \r\n");
      out.write("\t[<a href=\"list.jsp?pg=");
      out.print( i );
      out.write('"');
      out.write('>');
      out.print( i );
      out.write("</a>]\r\n");

    	} 
    } // end for

    if (totalPage >= next10) {

      out.write(" \r\n");
      out.write("\t<a href=\"list.jsp?pg=");
      out.print( next10 );
      out.write("\">다음</a>\r\n");

    } 

      out.write("\r\n");
      out.write("<a href=\"list.jsp?pg=");
      out.print( totalPage );
      out.write("\">bottom</a></td>\r\n");
      out.write("    \r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
