/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2016-11-26 17:40:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.homepage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/homepage/head.jsp", Long.valueOf(1480179855032L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<HTML>\r\n");
      out.write("<HEAD>\r\n");
      out.write("<TITLE>LOGIN</TITLE>\r\n");
      out.write("<META NAME=\"Generator\" CONTENT=\"EditPlus\">\r\n");
      out.write("<META NAME=\"Author\" CONTENT=\"\">\r\n");
      out.write("<META NAME=\"Keywords\" CONTENT=\"\">\r\n");
      out.write("<META NAME=\"Description\" CONTENT=\"\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("tr,td {\r\n");
      out.write(" border: 0px solid none;\r\n");
      out.write("}\r\n");
      out.write("#main-title {\r\n");
      out.write(" color: black;\r\n");
      out.write(" font-size: 65px;\r\n");
      out.write(" font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("#sub-title {\r\n");
      out.write(" color: black;\r\n");
      out.write(" font-size: 12pt;\r\n");
      out.write("}\r\n");
      out.write("#middle-title {\r\n");
      out.write(" color: black;\r\n");
      out.write(" font-size: 13pt;\r\n");
      out.write(" font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("k:hover {\r\n");
      out.write(" text-decoration: none;\r\n");
      out.write(" color: #FF1291\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write(" function gologin() {\r\n");
      out.write("  var frm3 = document.loginscreen;\r\n");
      out.write("  frm3.method = \"post\";\r\n");
      out.write("  frm3.action = \"./login.jsp\";\r\n");
      out.write("  frm3.submit();\r\n");
      out.write(" }\r\n");
      out.write(" function gohome() {\r\n");
      out.write("  var frm = document.loginscreen;\r\n");
      out.write("  frm.method = \"post\";\r\n");
      out.write("  frm.action = \"./home.jsp\"; //넘어간화면\r\n");
      out.write("  frm.submit(); //등록이 될수 있는 조건이면, 정보를 보내겠다.\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" function gojoin() {\r\n");
      out.write("  var frm = document.loginscreen;\r\n");
      out.write("  frm.method = \"post\";\r\n");
      out.write("  frm.action = \"./join.jsp\";\r\n");
      out.write("  frm.submit();\r\n");
      out.write(" }\r\n");
      out.write(" function goidfind(){\r\n");
      out.write("  var frm = document.loginscreen;\r\n");
      out.write("  frm.method = \"post\";\r\n");
      out.write("  frm.action = \"./id_find.jsp\";\r\n");
      out.write("  frm.submit();\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" function gopwfind(){\r\n");
      out.write("  var frm = document.loginscreen;\r\n");
      out.write("  frm.method = \"post\";\r\n");
      out.write("  frm.action = \"./pw_find.jsp\";\r\n");
      out.write("  frm.submit();\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" function enter() {\r\n");
      out.write("  var frm = document.loginscreen;\r\n");
      out.write("  if (frm.id.value.length < 3) {\r\n");
      out.write("   alert(\"아이디를 올바르게 입력해주세요\");\r\n");
      out.write("   return;\r\n");
      out.write("  }\r\n");
      out.write("  if (frm.pw.value.length < 3) {\r\n");
      out.write("   alert(\"비밀번호를 올바르게 입력해주세요\");\r\n");
      out.write("   return;\r\n");
      out.write("  }\r\n");
      out.write("  frm.method = \"post\";\r\n");
      out.write("  frm.action = \"./loginCtl.jsp\";\r\n");
      out.write("  frm.submit();\r\n");
      out.write(" }\r\n");
      out.write("</script>\r\n");
      out.write("</HEAD>\r\n");
      out.write("\r\n");
      out.write("<BODY>\r\n");
      out.write(" <form name=\"loginscreen\">\r\n");
      out.write("  ");
      out.write('\r');
      out.write('\n');

	String id = (String) session.getAttribute("idKey");
	String cPath = request.getContextPath();
	String url = "member.jsp";
	String label = "회원가입";
	
		if(id!=null) {
			url = "modifyMember.jsp";
			label = "회원수정";
		}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>head</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" \r\n");
      out.write("integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.1.1.min.js\"\r\n");
      out.write("  integrity=\"sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- Optional theme -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" integrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\" integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-default\">\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<a href=\"");
      out.print(cPath);
      out.write("/homepage/index.jsp\" target=\"_parent\" onFocus=\"this.blur();\"><img src=\"images/Pidgeotto.png\" width=\"50\"/></a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"chrto-navbar-collapse-1\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"active\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">메인 화면</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"");
      out.print(url);
      out.write("\" target=\"content\">회원가입</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\">조류 연구</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-haspopup=\"true\" aria-expanded=\"false\" >미드 연구<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">NCIS</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">왕좌의게임</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">워킹 데드</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-haspopup=\"true\" aria-expanded=\"false\" >게시판<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">자유 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">촉새 게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">벨몽 연구소</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("  <font face=\"Yang Rounded\">\r\n");
      out.write("   <table width=\"1330px\" border=\"0\" height=\"430px\" align=\"center\">\r\n");
      out.write("    <tr>\r\n");
      out.write("     <td>\r\n");
      out.write("      <table width=\"450px\" align=\"center\" border=\"0\"\r\n");
      out.write("       style=\"color: black; background-color: #F6F6F6; font-size: 30px; margin-top: -3%\">\r\n");
      out.write("       <tr>\r\n");
      out.write("        <td>\r\n");
      out.write("         <table width=\"750px\" align=\"center\" border=0\r\n");
      out.write("          style=\"background-color: white\">\r\n");
      out.write("          <tr>\r\n");
      out.write("           <td align=\"center\"><img src=\"../img/miki_icon.png\"\r\n");
      out.write("            height=\"30px \"></td>\r\n");
      out.write("           <td>LOGIN</td>\r\n");
      out.write("           <td><div id=\"sub-title\">| 로그인이 필요합니다.</td>\r\n");
      out.write("           <td width=\"300px\"></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("         </table>\r\n");
      out.write("        </td>\r\n");
      out.write("       </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("     \r\n");
      out.write("    <tr>\r\n");
      out.write("     <td>\r\n");
      out.write("      <table width=\"500px\" height=\"250px\" align=center \" border=\"8\"\r\n");
      out.write("       style=\"font-size: 20px; border-color: #F6F6F6; border-style: solid; margin-top: 2%\">\r\n");
      out.write("       <tr style=\"border: 0\">\r\n");
      out.write("        <td style=\"border: 0\">\r\n");
      out.write("         <table width=\"300px\" height=\"100px\" align=\"center\" border=\"0\">\r\n");
      out.write("          <tr align=\"center\">\r\n");
      out.write("           <td colspan=\"2\">* 아이디와 비밀번호를 입력해주세요</td>\r\n");
      out.write("          <tr align=\"center\">\r\n");
      out.write("           <td><br>ID <input type=\"text\" name=\"id\"\r\n");
      out.write("            style=\"width: 150px\"></td>\r\n");
      out.write("           <td rowspan=\"2\"><br>\r\n");
      out.write("           <input type=\"button\" name=\"login\" value=\"로그인\"\r\n");
      out.write("            onClick=\"enter()\" style=\"width: 60px; height: 60px\"></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr align=\"center\">\r\n");
      out.write("           <td>PW <input type=\"password\" name=\"pw\"\r\n");
      out.write("            style=\"width: 150px\"></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("         </table>\r\n");
      out.write("        </td>\r\n");
      out.write("       </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("     </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("  </font>\r\n");
      out.write(" </form>\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
