/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2016-11-28 11:23:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.homepage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div align=center>\r\n");
      out.write("<br/><br/><br/>\r\n");
      out.write("<h1>회원 가입</h1>\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"script.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction idCheck(id) {\r\n");
      out.write("\t\tfrm = document.regFrm;\r\n");
      out.write("\t\tif(id==\"\") {\r\n");
      out.write("\t\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t\tfrm.id.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\turl = \"idCheck.jsp?id=\" + id;\r\n");
      out.write("\t\twindow.open(url, \"IDCheck\", \"width=300, heigth=150\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction zipCheck() {\r\n");
      out.write("\t\turl = \"zipCheck.jsp?check=y\";\r\n");
      out.write("\t\twindow.open(url, \"ZipCodeSearch\", \"width=500, height=300, scrollbars=yes\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\t<form name=memberFrm  method=\"post\" action=\"memberProc.jsp\">\r\n");
      out.write("\t\t<table border=1 cellpadding=7 cellspacing=0 >\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td bgcolor=lightyellow>아이디 </td>\r\n");
      out.write("    \t\t\t<td align=left><input type=\"text\" name=\"id\"  maxlength=20>\r\n");
      out.write("    \t\t\t<input type=\"button\" value=\"ID중복확인\" onClick=\"idCheck(this.form.id.value)\">\r\n");
      out.write("    \t\t\t</td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td bgcolor=lightyellow>패스워드 </td> \r\n");
      out.write("    \t\t\t<td align=left><input type=\"password\" name=\"passwd\"  maxlength=20></td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td bgcolor=lightyellow>패스워드 확인 </td> \r\n");
      out.write("  \t\t\t    <td align=left><input type=\"password\" name=\"repasswd\"  maxlength=20></td>\r\n");
      out.write("  \t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td bgcolor=lightyellow>이름 </td> \r\n");
      out.write("    \t\t\t<td align=left><input type=\"text\" name=\"name\"  maxlength=20/></td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td bgcolor=lightyellow>성별</td>\r\n");
      out.write("   \t\t\t\t<td align=left><input type=\"radio\" name=\"gender\" value=\"남자\" checked>남자\r\n");
      out.write("   \t\t\t\t<input type=\"radio\" name=\"gender\" value=\"여자\">여자\r\n");
      out.write("   \t\t\t\t</td>\r\n");
      out.write("   \t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td bgcolor=lightyellow>이메일 </td>\r\n");
      out.write("  \t\t\t\t<td align=left><input type=\"text\" name=\"email\" maxlength=30 size=40></td>\r\n");
      out.write("  \t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td bgcolor=lightyellow>전화번호 </td>\r\n");
      out.write("  \t\t\t\t<td align=left><input type=\"text\" name=\"phone\" maxlength=30></td>\r\n");
      out.write("  \t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td bgcolor=lightyellow>우편번호</td>\r\n");
      out.write("   \t\t\t\t<td align=left><input type=\"text\" name=\"zipcode\" maxlength=7></td>\r\n");
      out.write("   \t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td bgcolor=lightyellow>주소 </td>\r\n");
      out.write("    \t\t\t<td align=left><input type=\"text\" name=\"address\" maxlength=30 size=60></td>\r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td bgcolor=lightyellow>직업</td>\r\n");
      out.write("   \t\t\t\t<td align=left><input type=\"text\" name=\"job\" maxlength=30 size=40></td>\r\n");
      out.write("   \t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=2 align=center><input type=\"submit\" value=\"회원가입\"> \r\n");
      out.write("    \t\t\t<input type=\"reset\" value=\"취소\"></td> \r\n");
      out.write("    \t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
