/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.72
 * Generated at: 2016-12-10 05:54:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.homepage.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Vector;
import board.*;
import java.text.SimpleDateFormat;

public final class listBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" \r\n");
      out.write("integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("  src=\"https://code.jquery.com/jquery-3.1.1.min.js\"\r\n");
      out.write("  integrity=\"sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=\"\r\n");
      out.write("  crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- Optional theme -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" integrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\" integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- 파일 boardForm.js : 폼의 각 입력 값이 있는지를 검토하는 함수 구현 -->\r\n");
      out.write("<script language=JavaScript src=\"boardForm.js\"></script>\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<center>\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/homepage/head.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"content\">\r\n");
      out.write("\t\t<h2>자유게시판 </h2>\r\n");
      out.write("\t\t<hr>  \r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\t");
 
				BoardMgr brddb = new BoardMgr();	 	
				Vector<BoardBean> list = brddb.getBoardList(); 
			   	int counter = list.size();
			   	int row = 0;
			   	
			   	if (counter > 0) {
			
      out.write("\r\n");
      out.write("\t\t    <table width=800  cellpadding=3 cellspacing=3 >\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t       <th width=60 bgcolor=lightgray><font color=blue><b>번호</b></font></th>\r\n");
      out.write("\t\t       <th width=430 bgcolor=lightgray><font color=blue><b>제목</b></font></th>\r\n");
      out.write("\t\t       <th width=80 bgcolor=lightgray><font color=blue><b>작성자</b></font></th>\r\n");
      out.write("\t\t       <th width=170 bgcolor=lightgray><font color=blue><b>작성일</b></font></th>\r\n");
      out.write("\t\t       <th width=60 bgcolor=lightgray><font color=blue><b>조회수</b></font></th>\r\n");
      out.write("\t\t    </tr>\r\n");
      out.write("\t\t\t");

				//게시 등록일을 2010-3-15 10:33:21 형태로 출력하기 위한 클래스 
				SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
				for( BoardBean brd : list ) {
					//홀짝으로 다르게 색상 지정
					String color = "papayawhip";
					if ( ++row % 2 == 0 ) color = "white"; 
			
      out.write("\r\n");
      out.write("\t\t    <tr bgcolor=");
      out.print(color );
      out.write(" \r\n");
      out.write("\t\t\t\tonmouseover=\"this.style.backgroundColor='SkyBlue'\"\r\n");
      out.write("\t\t    \tonmouseout=\"this.style.backgroundColor='");
      out.print(color );
      out.write("'\">\r\n");
      out.write("\t\t\t\t<!-- 수정과 삭제를 위한 링크로 id를 전송 -->\r\n");
      out.write("\t\t       <td align=center>");
      out.print( brd.getNum());
      out.write("</td>\r\n");
      out.write("\t\t       <td align=left><a href=\"readBoard.jsp?num=");
      out.print( brd.getNum());
      out.write('"');
      out.write('>');
      out.print( brd.getTitle() );
      out.write("</a></td>\r\n");
      out.write("\t\t       <td align=center>");
      out.print( brd.getName() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t<!-- 게시 작성일을 2010-3-15 10:33:21 형태로 출력 -->\r\n");
      out.write("\t\t       <td align=center>");
      out.print( df.format(brd.getRegdate()) );
      out.write("</td>\r\n");
      out.write("\t\t       <td align=center>");
      out.print( brd.getHit() );
      out.write("</td>\r\n");
      out.write("\t\t    </tr>\r\n");
      out.write("\t\t\t");

			    }  
			
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t");
 	}
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<hr width=80%>\r\n");
      out.write("\t\t<p>조회된 게시판 목록 수가 ");
      out.print(counter);
      out.write("개 입니다.\r\n");
      out.write("\t\t<br><br>\r\n");
      out.write("\t\t<form name=form method=post action=\"editBoard.jsp\">\r\n");
      out.write("\t\t      <input type=submit value=\"글쓰기\"> \r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"foot\">\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/homepage/foot.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
